Feature/show posts
CodeSoom/project-react-4-dngwoodo pull request #1
Opened 2021-07-02 00:47 UTC by dngwoodo

- [  ] 프로젝트 셋팅
- [  ] 마크다운을 화면에 표시

2021-07-02 13:38 UTC, Kihyun92 requested changes
prop-templates 폴더 내의 파일들도 깃으로 관리되어야하는 부분인가요? 매번 변경이 되는 부분인지 궁금하네요~

2021-07-02 13:38 UTC, Kihyun92 commented on README.md
> +# Side Project
README를 작성해주셨군요 👍🏼 

지금은 동우님 관점에서 작성된 리드미 같아요.

다른 사람들에게 조금 더 이 서비스에 대해서 설명해줘도 좋을 것 같네요~

2021-07-02 13:38 UTC, Kihyun92 commented on components/Post/Post.tsx
> +    <li key={slug}>
상위 부모 컴포넌트에서 사용할 때 key값을 지정해줬기 때문에 여기서 key를 지정해줄 필요 없지 않나요??

2021-07-02 13:38 UTC, Kihyun92 commented on components/Post/Post.tsx
> +import PostType from '@/types/PostType';
Post와 같이 전역적으로 사용하는 커스텀 타입의 경우엔 `d.ts`를 사용해서 따로 파일로 만들면 매번 타입을 임포트하지 않아도 됩니다~

- https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html

2021-07-02 13:42 UTC, Kihyun92 commented
개인 프로젝트부터는 PR을 작은 기능 단위로 구현해주세요! 

해당 기능 구현이 완료되면 PR을 본인이 머지해주시면 됩니다.

2021-07-04 14:00 UTC, dngwoodo commented on README.md
> +# Side Project
다음 PR에서 변경해보겠습니다!

2021-07-04 14:08 UTC, dngwoodo commented on components/Post/Post.tsx
> +import PostType from '@/types/PostType';
이 부분은 슬랙으로 질문을 남겼습니다. 이해가 어렵네요 ㅠ

2021-07-04 14:09 UTC, dngwoodo commented on components/Post/Post.tsx
> +    <li key={slug}>
피드백 감사합니다. https://github.com/CodeSoom/project-react-4-dngwoodo/pull/1/commits/8d20b6167fe48a1a03c091a1d36593538267b7d1 에서 적용했습니다.

2021-07-04 14:09 UTC, dngwoodo commented
> prop-templates 폴더 내의 파일들도 깃으로 관리되어야하는 부분인가요? 매번 변경이 되는 부분인지 궁금하네요~

아 이 부분은 굳이 올릴필요가 없었네요. 우선 gitignore에 추가해두었습니다. 이미 깃헙에 올라간 아이는 어떻게 빼줘야 할까요?

2021-07-04 14:10 UTC, merged